apiVersion: v1
kind: Service
metadata:
  name: whale-service
  labels:
    app.kubernetes.io/name: whale-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8084
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: whale-service
