apiVersion: v1
kind: ConfigMap
metadata:
  name: news-service-env-config
data:
  TZ: "UTC"
  QUARKUS_HTTP_PORT: "8082"
  QUARKUS_LOG_LEVEL: "INFO"
  QUARKUS_REDIS_HOSTS: "redis://redis:6379"
  QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://cryptonews-db-rw:5432/cryptonews"
